apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-config
  namespace: devops-l3gl
data:
  MYSQL_HOST: mysql
  MYSQL_USER: root
  LOKI_URL: http://host.minikube.internal:3100/loki/api/v1/push
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: devops-l3gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-api
          image: docker.io/moussacench/product-api:latest
          ports:
            - containerPort: 8086
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: MYSQL_USER
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: product-api-config
                  key: LOKI_URL
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
            limits:
              cpu: 400m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-api-service
  namespace: devops-l3gl
spec:
  selector:
    app: product-api
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-api-ingress
  namespace: devops-l3gl
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: product-api-service
                port:
                  number: 8086
